### ISSUE TITLE
Timeout on slower machines a little low

### ISSUE THREAD

**Issue by steevaavoo** [JRHemmen/ansible_role_roon_core#1]
Hey there.

I've been playing around with Ansible to automate building of Roon cores and happened across your module - very impressive!

One thing I noticed was that the final task of running the Roon installer script would time out before the Y/n prompt came up - so I bumped it to 60 seconds and it worked a treat - might be worth increasing? I'm happy to do it and chuck in a PR.

**Comment by JRHemmen** [comment]
Hey, good find! I upped it to 60s and cut a new release v0.1.2.
